# Generated by Django 4.0.1 on 2022-01-31 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleshopping',
            name='dataatualizado',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 23, 23, 13, 267303)),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='dataatualizado',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 23, 23, 13, 265302)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='dataatualizado',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 23, 23, 13, 260302)),
        ),
    ]
