# Generated by Django 4.0.1 on 2022-01-31 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_alter_categoriasprodutos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasprodutos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoriasprodutos',
            name='idcategoria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='categoriasprodutos',
            name='iddepartamento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='googleshopping',
            name='dataatualizado',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 1, 51, 46, 943249), null=True),
        ),
        migrations.AlterField(
            model_name='googleshopping',
            name='googleid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='dataatualizado',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 1, 51, 46, 940249), null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='idproduto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='dataatualizado',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 1, 51, 46, 937249), null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='idseller',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='idusuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
