# Generated by Django 4.0.1 on 2022-01-31 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0018_alter_googleshopping_dataatualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleshopping',
            name='dataatualizado',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 4, 23, 55, 89792), null=True),
        ),
        migrations.AlterField(
            model_name='googleshopping',
            name='googleid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='dataatualizado',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 4, 23, 55, 87791), null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='dataatualizado',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 31, 4, 23, 55, 83792), null=True),
        ),
    ]
